const imgSources = {
   "african fan palm": require('UgandaTrees/src/assets/images/african-fan-palm.jpg'), 
   "african oil palm": require('UgandaTrees/src/assets/images/african-oil-palm.jpg'), 
   "alexandra palm": require('UgandaTrees/src/assets/images/alexandra-palm.jpg'), 
   "black plum": require('UgandaTrees/src/assets/images/black-plum.jpeg'), 
   "bombax": require('UgandaTrees/src/assets/images/bombax.jpg'), 
   "bottlebrush": require('UgandaTrees/src/assets/images/bottlebrush.jpg'), 
   "breadfruit": require('UgandaTrees/src/assets/images/breadfruit.jpg'), 
   "cabbage palm": require('UgandaTrees/src/assets/images/cabbage-palm.jpg'), 
   "caja fruit": require('UgandaTrees/src/assets/images/caja-fruit.jpg'), 
   "calabash nutmeg": require('UgandaTrees/src/assets/images/calabash-nutmeg.jpg'), 
   "candle bush": require('UgandaTrees/src/assets/images/candle-bush.jpg'), 
   "candle-nut": require('UgandaTrees/src/assets/images/candle-nut.jpg'), 
   "cassia": require('UgandaTrees/src/assets/images/cassia.png'), 
   "croton": require('UgandaTrees/src/assets/images/croton.png'), 
   "drum tree": require('UgandaTrees/src/assets/images/drum-tree.jpg'), 
   "east african green wood": require('UgandaTrees/src/assets/images/east-african-green-wood.jpg'), 
   "english yellow mulberry": require('UgandaTrees/src/assets/images/english-yellow-mulberry.jpg'), 
   "false muvule (kirudu)": require('UgandaTrees/src/assets/images/false-muvule-(kirudu).jpg'), 
   "granite mangosteen": require('UgandaTrees/src/assets/images/granite-mangosteen.jpg'), 
   "guava": require('UgandaTrees/src/assets/images/guava.jpeg'), 
   "iroko": require('UgandaTrees/src/assets/images/iroko.jpg'), 
   "jackfruit": require('UgandaTrees/src/assets/images/jackfruit.jpg'), 
   "jumping seed tree": require('UgandaTrees/src/assets/images/jumping-seed-tree.jpg'), 
   "kapok": require('UgandaTrees/src/assets/images/kapok.jpg'), 
   "lemon-scented gum": require('UgandaTrees/src/assets/images/lemon-scented-gum.jpg'), 
   "loquat": require('UgandaTrees/src/assets/images/loquat.jpg'), 
   "mango": require('UgandaTrees/src/assets/images/mango.jpg'), 
   "mpewere": require('UgandaTrees/src/assets/images/mpewere.jpeg'), 
   "mugavu": require('UgandaTrees/src/assets/images/mugavu.jpg'), 
   "mukookowe": require('UgandaTrees/src/assets/images/mukookowe.jpeg'), 
   "mukuzanyana": require('UgandaTrees/src/assets/images/mukuzanyana.jpg'), 
   "mulongo": require('UgandaTrees/src/assets/images/mulongo.jpeg'), 
   "musizi": require('UgandaTrees/src/assets/images/musizi.jpeg'), 
   "mutuba": require('UgandaTrees/src/assets/images/mutuba.jpg'), 
   "muvule": require('UgandaTrees/src/assets/images/muvule.jpeg'), 
   "muwafu": require('UgandaTrees/src/assets/images/muwafu.jpg'), 
   "muziru": require('UgandaTrees/src/assets/images/muziru.jpg'), 
   "norfolk island pine": require('UgandaTrees/src/assets/images/norfolk-island-pine.jpeg'), 
   "paper mulberry": require('UgandaTrees/src/assets/images/paper-mulberry.jpg'), 
   "parasol": require('UgandaTrees/src/assets/images/parasol.jpg'), 
   "pheasant-berry": require('UgandaTrees/src/assets/images/pheasant-berry.jpg'), 
   "pitanga cherry": require('UgandaTrees/src/assets/images/pitanga-cherry.jpg'), 
   "podo": require('UgandaTrees/src/assets/images/podo.jpg'), 
   "queensland umbrella tree": require('UgandaTrees/src/assets/images/queensland-umbrella-tree.jpeg'), 
   "raffia palm": require('UgandaTrees/src/assets/images/raffia-palm.jpg'), 
   "red mahogany": require('UgandaTrees/src/assets/images/red-mahogany.jpeg'), 
   "red nongo": require('UgandaTrees/src/assets/images/red-nongo.jpg'), 
   "sausage tree": require('UgandaTrees/src/assets/images/sausage-tree.jpg'), 
   "soursop": require('UgandaTrees/src/assets/images/soursop.jpg'), 
   "star fruit": require('UgandaTrees/src/assets/images/star-fruit.jpg'), 
   "terminalia": require('UgandaTrees/src/assets/images/terminalia.jpg'), 
   "tipu": require('UgandaTrees/src/assets/images/tipu.jpg'), 
   "toddy palm": require('UgandaTrees/src/assets/images/toddy-palm.jpeg')
}

export default imgSources;